# This file was generated by GoReleaser. DO NOT EDIT.
class CloudInstanceDns < Formula
  desc "A DNS that will look up aws(ec2), gcp(compute-engine) regardless of multi regions by instance-name or id."
  homepage ""
  version "1.0.0"

  if OS.mac?
    url "https://github.com/gjbae1212/cloud-instance-dns/releases/download/v1.0.0/cloud-instance-dns_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "7fcf5b4519c6e7eeafb513654bdbbb35cabddc2c8bec047784f41dea0c0c624e"
  elsif OS.linux?
    url "https://github.com/gjbae1212/cloud-instance-dns/releases/download/v1.0.0/cloud-instance-dns_1.0.0_Linux_x86_64.tar.gz"
    sha256 "353d9fdc20be0abb5b74b5acca5763e7bc320b79e70832e42299a9c655b8fc99"
  end

  def install
    bin.install "cloud-instance-dns"
  end
end
