# This file was generated by GoReleaser. DO NOT EDIT.
class CloudInstanceDns < Formula
  desc "A DNS that will look up aws(ec2), gcp(compute-engine) regardless of multi regions by instance-name or id."
  homepage ""
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gjbae1212/cloud-instance-dns/releases/download/v1.1.0/cloud-instance-dns_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "f5be3bbedfeae115a7b265824f06ed0c0aed02f5785351b1c13d029352b8c97a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gjbae1212/cloud-instance-dns/releases/download/v1.1.0/cloud-instance-dns_1.1.0_Linux_x86_64.tar.gz"
      sha256 "95e3f96c89892fa9907b3e359e9b1f6d36772450d192840ba2f08249afa9b811"
    end
  end

  def install
    bin.install "cloud-instance-dns"
  end
end
